version: '3.6'

services: 
    backend-app:
        build : .
        ports:
            - 8000:8000
        depends_on:
            - mysql-db
    
    mysql-db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root123
        ports:
            - 3000:3306
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql-db: